services:
  mongo:
    image: mongo:7
    container_name: hg_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: healthguard
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ../api
    container_name: hg_api
    restart: unless-stopped
    environment:
      ENV: dev
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: healthguard
      MAX_IMAGE_MB: "8"
      # MODELS_DIR doit contenir model.tflite (tu mettras un dummy au d√©but)
      MODELS_DIR: /app/models
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ../api/models:/app/models:ro

volumes:
  mongo_data:
